export const AddWeatherData="Add Data";
export const AddCity="Add City";
export const AddUnit="Add Unit";
export const AddDb="Add Db";
export const User_List="User Data";
export const AddStar="Add star";
export const SetUserData="Set user data";
export const GET_USER_FETCH='GET_USER_FETCH';
export const GET_USER_SUCCESS='GET_USER_SUCCESS'